package com.xlh.chat.model;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;

public class UserRequestMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_request_msg.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_request_msg.request_user_id
     *
     * @mbg.generated
     */
    private Long requestUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_request_msg.receive_user_id
     *
     * @mbg.generated
     */
    private Long receiveUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_request_msg.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_request_msg.request_msg
     *
     * @mbg.generated
     */
    private String requestMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_request_msg.create_time
     *
     * @mbg.generated
     */
    private Timestamp createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_request_msg.modify_time
     *
     * @mbg.generated
     */
    private Timestamp modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_request_msg.id
     *
     * @return the value of user_request_msg.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_request_msg.id
     *
     * @param id the value for user_request_msg.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_request_msg.request_user_id
     *
     * @return the value of user_request_msg.request_user_id
     *
     * @mbg.generated
     */
    public Long getRequestUserId() {
        return requestUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_request_msg.request_user_id
     *
     * @param requestUserId the value for user_request_msg.request_user_id
     *
     * @mbg.generated
     */
    public void setRequestUserId(Long requestUserId) {
        this.requestUserId = requestUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_request_msg.receive_user_id
     *
     * @return the value of user_request_msg.receive_user_id
     *
     * @mbg.generated
     */
    public Long getReceiveUserId() {
        return receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_request_msg.receive_user_id
     *
     * @param receiveUserId the value for user_request_msg.receive_user_id
     *
     * @mbg.generated
     */
    public void setReceiveUserId(Long receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_request_msg.status
     *
     * @return the value of user_request_msg.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_request_msg.status
     *
     * @param status the value for user_request_msg.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_request_msg.request_msg
     *
     * @return the value of user_request_msg.request_msg
     *
     * @mbg.generated
     */
    public String getRequestMsg() {
        return requestMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_request_msg.request_msg
     *
     * @param requestMsg the value for user_request_msg.request_msg
     *
     * @mbg.generated
     */
    public void setRequestMsg(String requestMsg) {
        this.requestMsg = requestMsg == null ? null : requestMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_request_msg.create_time
     *
     * @return the value of user_request_msg.create_time
     *
     * @mbg.generated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_request_msg.create_time
     *
     * @param createTime the value for user_request_msg.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_request_msg.modify_time
     *
     * @return the value of user_request_msg.modify_time
     *
     * @mbg.generated
     */
    public Timestamp getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_request_msg.modify_time
     *
     * @param modifyTime the value for user_request_msg.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table user_request_msg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        requestUserId("request_user_id", "requestUserId", "BIGINT", false),
        receiveUserId("receive_user_id", "receiveUserId", "BIGINT", false),
        status("status", "status", "TINYINT", false),
        requestMsg("request_msg", "requestMsg", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_request_msg
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}