package com.xlh.chat.dao.mapper;

import com.xlh.chat.model.LocalAuth;
import com.xlh.chat.model.LocalAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocalAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    long countByExample(LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    int deleteByExample(LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    int insert(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    int insertSelective(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    List<LocalAuth> selectByExample(LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    LocalAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LocalAuth record, @Param("example") LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LocalAuth record, @Param("example") LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<LocalAuth> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<LocalAuth> list, @Param("selective") LocalAuth.Column ... selective);
}