package com.xlh.chat.dao.mapper;

import com.xlh.chat.model.UserRequestMsg;
import com.xlh.chat.model.UserRequestMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRequestMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    long countByExample(UserRequestMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    int deleteByExample(UserRequestMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    int insert(UserRequestMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    int insertSelective(UserRequestMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    List<UserRequestMsg> selectByExample(UserRequestMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    UserRequestMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserRequestMsg record, @Param("example") UserRequestMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserRequestMsg record, @Param("example") UserRequestMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRequestMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRequestMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<UserRequestMsg> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_request_msg
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<UserRequestMsg> list, @Param("selective") UserRequestMsg.Column ... selective);
}