package com.xlh.chat.dao.mapper;

import com.xlh.chat.model.UserInfo;
import com.xlh.chat.model.UserInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapperExtend {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    Long insertSelectiveReturnId(UserInfo record);

    /**
     * 根据手机号查找用户信息
     *
     * @param phone
     * @return
     */
    UserInfo selectByPhone(String phone);

}
