package com.xlh.chat.model.dto;

import lombok.Data;

import java.io.Serializable;
import java.sql.Timestamp;

@Data
public class ChatHistoryDto implements Serializable {
    private static final long serialVersionUID = -5287609496488264028L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.send_user_id
     *
     * @mbg.generated
     */
    private Long sendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.receive_user_id
     *
     * @mbg.generated
     */
    private Long receiveUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.send_time
     *
     * @mbg.generated
     */
    private Timestamp sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.create_time
     *
     * @mbg.generated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.modify_time
     *
     * @mbg.generated
     */
    private Timestamp modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.msg_type
     *
     * @mbg.generated
     */
    private Integer msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.chat_type
     *
     * @mbg.generated
     */
    private Integer chatType;
}
