package com.xlh.chat.model.dto;

import lombok.Data;

import java.io.Serializable;
import java.sql.Timestamp;

@Data
public class ChatHistoryDto implements Serializable {
    private static final long serialVersionUID = -5287609496488264028L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.send_user_id
     *
     * @mbg.generated
     */
    private Long sendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.receive_user_id
     *
     * @mbg.generated
     */
    private Long receiveUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.send_time
     *
     * @mbg.generated
     */
    private Timestamp sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.create_time
     *
     * @mbg.generated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.modify_time
     *
     * @mbg.generated
     */
    private Timestamp modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.msg_type
     *
     * @mbg.generated
     */
    private Integer msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat_history.chat_type
     *
     * @mbg.generated
     */
    private Integer chatType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.id
     *
     * @return the value of user_chat_history.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.id
     *
     * @param id the value for user_chat_history.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.send_user_id
     *
     * @return the value of user_chat_history.send_user_id
     * @mbg.generated
     */
    public Long getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.send_user_id
     *
     * @param sendUserId the value for user_chat_history.send_user_id
     * @mbg.generated
     */
    public void setSendUserId(Long sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.receive_user_id
     *
     * @return the value of user_chat_history.receive_user_id
     * @mbg.generated
     */
    public Long getReceiveUserId() {
        return receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.receive_user_id
     *
     * @param receiveUserId the value for user_chat_history.receive_user_id
     * @mbg.generated
     */
    public void setReceiveUserId(Long receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.group_id
     *
     * @return the value of user_chat_history.group_id
     * @mbg.generated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.group_id
     *
     * @param groupId the value for user_chat_history.group_id
     * @mbg.generated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.message
     *
     * @return the value of user_chat_history.message
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.message
     *
     * @param message the value for user_chat_history.message
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.send_time
     *
     * @return the value of user_chat_history.send_time
     * @mbg.generated
     */
    public Timestamp getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.send_time
     *
     * @param sendTime the value for user_chat_history.send_time
     * @mbg.generated
     */
    public void setSendTime(Timestamp sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.create_time
     *
     * @return the value of user_chat_history.create_time
     * @mbg.generated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.create_time
     *
     * @param createTime the value for user_chat_history.create_time
     * @mbg.generated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.modify_time
     *
     * @return the value of user_chat_history.modify_time
     * @mbg.generated
     */
    public Timestamp getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.modify_time
     *
     * @param modifyTime the value for user_chat_history.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.msg_type
     *
     * @return the value of user_chat_history.msg_type
     * @mbg.generated
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.msg_type
     *
     * @param msgType the value for user_chat_history.msg_type
     * @mbg.generated
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat_history.chat_type
     *
     * @return the value of user_chat_history.chat_type
     * @mbg.generated
     */
    public Integer getChatType() {
        return chatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat_history.chat_type
     *
     * @param chatType the value for user_chat_history.chat_type
     * @mbg.generated
     */
    public void setChatType(Integer chatType) {
        this.chatType = chatType;
    }
}
