package com.xlh.chat.model.dto;

import lombok.Data;

import java.io.Serializable;
/**
 * 用途描述
 *
 * @author 胡晓磊
 * @company xxx
 * @date 2020年04月25日 17:04 胡晓磊 Exp $
 */
@Data
public class UserInfoDto implements Serializable {
    private static final long serialVersionUID = 7848877058581389645L;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nick_name
     *
     * @mbg.generated
     * 昵称
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.avatar
     *
     * @mbg.generated
     * 头像地址
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbg.generated
     * 性别
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbg.generated
     * 邮箱地址
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.region
     *
     * @mbg.generated
     * 区域
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_auth.user_name
     *
     * @mbg.generated
     * 用户名
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_auth.password
     *
     * @mbg.generated
     * 密码
     */
    private String password;
}
